# yaml-language-server: $schema=https://schema.blue-build.org
name: butrelinux
description: Bluefin GDX on KDE

base-image: ghcr.io/ublue-os/bluefin-gdx
image-version: lts

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      # Install the repo packages from the local files you just added
      - /tmp/files/rpms/rpmfusion-free-release-10-0.1.noarch.rpm
      - /tmp/files/rpms/rpmfusion-nonfree-release-10-0.1.noarch.rpm
      # Core packages
      - fastfetch
      - micro
      - starship
      - steam
      - btop
      - mangohud
      - gamemode
      - sddm
      - power-profiles-daemon
      - nvtop
      - xdg-desktop-portal-kde
      - pipewire-codec-aptx
      # KDE Plasma Core
      - plasma-desktop
      - plasma-workspace-wayland
      - kde-settings-plasma
      - kscreen
      - kinfocenter
      - dolphin
      - konsole
      - sddm-kcm
      - sddm-breeze
    remove:
      - firefox
      - firefox-langpacks
      - gnome-shell
      - gdm

  - type: kargs
    kargs:
      - nvidia-drm.modeset=1
      - nvidia.NVreg_PreserveVideoMemoryAllocations=1
      - rd.driver.blacklist=nouveau
      - modprobe.blacklist=nouveau
      - amdgpu.ppfeaturemask=0xffffffff
      - acpi_backlight=vendor
      - split_lock_detect=off

  - type: systemd
    system:
      enabled:
        - sddm.service
        - power-profiles-daemon.service
      disabled:
        - gdm.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.kde.gwenview
          - it.miosemante.gearlever
      - scope: user

  - type: signing
