# yaml-language-server: $schema=https://schema.blue-build.org
name: butrelinux
description: Bluefin-GDX with KDE

base-image: ghcr.io/ublue-os/bluefin-gdx
image-version: lts

modules:
  - type: files
    files:
      - source: rpms # This takes files/rpms/*
        destination: /rpms # and puts them in /rpms/ inside the image
      - source: system
        destination: /

  # Stage 1: Install the local RPMs to activate the repos
  - type: dnf
    install:
      packages:
        - /rpms/rpmfusion-free-release-10.noarch.rpm
        - /rpms/rpmfusion-nonfree-release-10.noarch.rpm

  # Stage 2: Install the packages now that the repos are active
  - type: rpm-ostree
    install:
      - fastfetch
      - micro
      - starship
      - steam
      - btop
      - mangohud
      - gamemode
      - sddm
      - power-profiles-daemon
      - nvtop
      - xdg-desktop-portal-kde
      - pipewire-codec-aptx
      - plasma-desktop
      - plasma-workspace-wayland
      - kde-settings-plasma
      - kscreen
      - kinfocenter
      - dolphin
      - konsole
      - sddm-kcm
      - sddm-breeze
    remove:
      - gnome-shell
      - gdm

  - type: kargs
    kargs:
      - nvidia-drm.modeset=1
      - nvidia.NVreg_PreserveVideoMemoryAllocations=1
      - rd.driver.blacklist=nouveau
      - modprobe.blacklist=nouveau
      - amdgpu.ppfeaturemask=0xffffffff
      - acpi_backlight=vendor
      - split_lock_detect=off

  - type: systemd
    system:
      enabled:
        - sddm.service
        - power-profiles-daemon.service
      disabled:
        - gdm.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.kde.gwenview
          - it.miosemante.gearlever
      - scope: user

  - type: signing
