name: E2E Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: projectbluefin/testsuite/.github/workflows/e2e.yml@v1
    with:
      image: ghcr.io/butrejp/butrelinux-experimental:latest
      suites: kde-smoke,common,lifecycle,security,hardware
